name = "GraphPPL"
uuid = "b3f8163a-e979-4e85-b43e-1f63d8c8b42c"
authors = ["Wouter Nuijten <wouternuijten@gmail.com>", "Dmitry Bagaev <bvdmitri@gmail.com>"]
version = "4.0.1"

[deps]
BitSetTuples = "0f2f92aa-23a3-4d05-b791-88071d064721"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
MetaGraphsNext = "fa8bd995-216d-47f1-8a91-f3b68fbeb377"
NamedTupleTools = "d9ec5142-1e00-5aa0-9d6a-321866360f50"
Static = "aedffcd0-7271-4cad-89d0-dc628f76c6d3"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TupleTools = "9d95972d-f1c8-5527-a6e0-b4b365fa01f6"
Unrolled = "9602ed7d-8fef-5bc8-8597-8f21381861e8"

[weakdeps]
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GraphPlot = "a2cc645c-3eea-5389-862e-a155d0052231"

[extensions]
GraphPPLDistributionsExt = "Distributions"
GraphPPLPlottingExt = ["Cairo", "GraphPlot"]

[compat]
BitSetTuples = "1.1"
Cairo = "1.0"
DataStructures = "0.18"
Dictionaries = "0.4"
Distributions = "0.25"
Documenter = "1.0"
GraphPlot = "0.5"
MacroTools = "0.5"
MetaGraphsNext = "0.6, 0.7"
NamedTupleTools = "0.14"
Static = "0.8"
StaticArrays = "1.6"
TupleTools = "1.4"
Unrolled = "0.1"
julia = "1.6"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[targets]
test = ["Documenter"]
